### ISSUE TITLE
Missing LICENSE

### ISSUE THREAD

**Issue by TechnologyClassroom** [OpMonTeam/OpMon-Godot#11]
I see you have no LICENSE file for this project. The default is copyright.

I would suggest releasing the code under the GPL-3.0-or-later or AGPL-3.0-or-later license so that others are encouraged to contribute changes back to your project.

**Comment by cyriellecentori** [comment]
Sorry for the wait, I was in hiatus! It is just an oversight, the license is the same as the original OpMon game, I'll add the file right away!
